x-solr-service: &solr-service
  image: solr:9.8.0
  ports:
    - "8983:8983"
  command:
    - "-Denable.packages=true -Dsolr.modules=llm"
  volumes:
    - "./solr/solr.in.sh:/etc/default/solr.in.sh"
    - "./solr/conf/idcc_conf:/opt/solr/server/solr/configsets/idcc/conf"
    - "./solr/logs:/var/solr/logs"
    - "./solr/data:/var/solr/data"
  depends_on:
    - zookeeper1
  links:
    - mysql

x-zookeeper-service: &zookeeper-service
  image: zookeeper:3.7
  environment:
    ZOO_MY_ID: 1
    ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181
    ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok

x-batch-service: &batch-service
  build: ./batch/
  volumes:
    - ./batch:/workspace/app
  working_dir: /workspace/app
  tty: true
  links:
    - solr_node1
    - zookeeper1
    - mysql

x-mysql-service: &mysql-service
  image: mysql:8.0
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=lcc
    - MYSQL_USER=solrtutorial
    - MYSQL_PASSWORD=solrtutorial
  ports:
    - "3306:3306"
  volumes:
    - "./mysql/data/:/data/"
    - "./mysql/sql/:/docker-entrypoint-initdb.d/"
    - "./mysql/conf.d:/etc/mysql/conf.d"

services:
  solr_node1:
    <<: *solr-service
    container_name: solr_node1
    profiles:
      - basic
  zookeeper1:
    <<: *zookeeper-service
    container_name: zookeeper1
    profiles:
      - basic
  batch:
    <<: *batch-service
    container_name: batch
    profiles:
      - basic
  mysql:
    <<: *mysql-service
    container_name: mysql
    profiles:
      - basic
